language: objective-c
osx_image: xcode7.3
xcode_workspace: Asterank.xcworkspace
xcode_scheme: Asterank
before_install:
- sudo gem install cocoapods
- pod setup
- pod install
- brew update
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
script:
- xctool -workspace Asterank.xcworkspace -scheme Asterank build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO